"use server";

import { readFile, writeFile } from "fs/promises";
import { resolve } from "path";

import { createClient } from "@supabase/supabase-js";
import prisma from "@Batman/db";

const STORAGE_BUCKETS = ["avatars", "uploads", "attachments"] as const;

const ENV_PATH = resolve(process.cwd(), ".env");

export async function getSetupStatus() {
  try {
    const content = await readFile(ENV_PATH, "utf-8");
    const lines = content.split("\n").filter((l) => l.trim() && !l.startsWith("#"));
    const vars: Record<string, string> = {};
    for (const line of lines) {
      const eqIdx = line.indexOf("=");
      if (eqIdx === -1) continue;
      const key = line.slice(0, eqIdx).trim();
      const val = line.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, "");
      vars[key] = val;
    }

    return {
      exists: true,
      configured: !!(vars.DATABASE_URL && vars.BETTER_AUTH_SECRET),
      vars: {
        hasDatabase: !!vars.DATABASE_URL,
        hasDirectUrl: !!vars.DIRECT_URL,
        hasAuthSecret: !!vars.BETTER_AUTH_SECRET,
        hasAuthUrl: !!vars.BETTER_AUTH_URL,
        hasCors: !!vars.CORS_ORIGIN,
        hasSupabaseUrl: !!(vars.SUPABASE_URL || vars.NEXT_PUBLIC_SUPABASE_URL),
        hasSupabaseKey: !!(vars.SUPABASE_SERVICE_ROLE_KEY || vars.NEXT_PUBLIC_SUPABASE_ANON_KEY),
        hasResend: !!vars.RESEND_API_KEY,
        hasGoogle: !!(vars.GOOGLE_CLIENT_ID && vars.GOOGLE_CLIENT_SECRET),
      },
    };
  } catch {
    return {
      exists: false,
      configured: false,
      vars: {
        hasDatabase: false,
        hasDirectUrl: false,
        hasAuthSecret: false,
        hasAuthUrl: false,
        hasCors: false,
        hasSupabaseUrl: false,
        hasSupabaseKey: false,
        hasResend: false,
        hasGoogle: false,
      },
    };
  }
}

const DB_PASSWORD_PLACEHOLDER = "[YOUR-PASSWORD]";

type SetupData = {
  databaseUrl: string;
  directUrl: string;
  databasePassword?: string;
  betterAuthUrl: string;
  corsOrigin: string;
  supabaseUrl?: string;
  supabaseAnonKey?: string;
  supabaseServiceRoleKey?: string;
  resendApiKey?: string;
  googleClientId?: string;
  googleClientSecret?: string;
  emailVerificationEnabled?: boolean;
  forgotPasswordEnabled?: boolean;
  polarAccessToken?: string;
  polarOrganizationId?: string;
  polarWebhookSecret?: string;
  polarSandboxMode?: boolean;
};

function embedPasswordInUrl(url: string, password: string): string {
  if (!url.includes(DB_PASSWORD_PLACEHOLDER)) return url;
  const encoded = encodeURIComponent(password);
  return url.replaceAll(DB_PASSWORD_PLACEHOLDER, encoded);
}

export async function saveSetup(data: SetupData) {
  const betterAuthSecret = await generateAuthSecret();

  let databaseUrl = data.databaseUrl;
  let directUrl = data.directUrl;
  if (data.databasePassword) {
    databaseUrl = embedPasswordInUrl(databaseUrl, data.databasePassword);
    directUrl = embedPasswordInUrl(directUrl, data.databasePassword);
  }

  const lines: string[] = [
    "# Generated by Batman Setup Wizard",
    "",
    "# Auth (required)",
    `BETTER_AUTH_SECRET=${betterAuthSecret}`,
    `BETTER_AUTH_URL=${data.betterAuthUrl}`,
    `CORS_ORIGIN=${data.corsOrigin}`,
    "",
    "# Database (required)",
    `DATABASE_URL="${databaseUrl}"`,
    `DIRECT_URL="${directUrl}"`,
  ];

  if (data.supabaseUrl || data.supabaseAnonKey || data.supabaseServiceRoleKey) {
    lines.push("", "# Supabase (file uploads)");
    if (data.supabaseUrl) {
      lines.push(`SUPABASE_URL=${data.supabaseUrl}`);
      lines.push(`NEXT_PUBLIC_SUPABASE_URL=${data.supabaseUrl}`);
    }
    if (data.supabaseAnonKey) {
      lines.push(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${data.supabaseAnonKey}`);
    }
    if (data.supabaseServiceRoleKey) {
      lines.push(`SUPABASE_SERVICE_ROLE_KEY=${data.supabaseServiceRoleKey}`);
    }
  }

  if (data.resendApiKey) {
    lines.push("", "# Email (Resend)");
    lines.push(`RESEND_API_KEY=${data.resendApiKey}`);
  }

  if (data.googleClientId && data.googleClientSecret) {
    lines.push("", "# Google OAuth");
    lines.push(`GOOGLE_CLIENT_ID=${data.googleClientId}`);
    lines.push(`GOOGLE_CLIENT_SECRET=${data.googleClientSecret}`);
  }

  lines.push("");

  await writeFile(ENV_PATH, lines.join("\n"), "utf-8");

  if (data.supabaseUrl && data.supabaseServiceRoleKey) {
    try {
      const supabase = createClient(data.supabaseUrl, data.supabaseServiceRoleKey);
      for (const bucket of STORAGE_BUCKETS) {
        const { error } = await supabase.storage.createBucket(bucket, { public: true });
        if (error && !error.message?.toLowerCase().includes("already exists")) {
          console.warn(`Supabase storage: could not create bucket "${bucket}":`, error.message);
        }
      }
    } catch (e) {
      console.warn("Supabase storage: could not create buckets:", e);
    }
  }

  const hasGoogle = !!(data.googleClientId && data.googleClientSecret);
  const hasSocial = hasGoogle;
  const hasAuthSettings =
    hasSocial ||
    data.resendApiKey ||
    data.emailVerificationEnabled !== undefined ||
    data.forgotPasswordEnabled !== undefined ||
    data.polarAccessToken ||
    data.polarWebhookSecret;

  if (hasAuthSettings) {
    try {
      await prisma.appSettings.upsert({
        where: { id: "default" },
        update: {
          ...(hasSocial && {
            googleClientId: hasGoogle ? data.googleClientId! : null,
            googleClientSecret: hasGoogle ? data.googleClientSecret! : null,
            socialLoginEnabled: hasSocial,
          }),
          ...(data.resendApiKey !== undefined && {
            resendApiKey: data.resendApiKey || null,
          }),
          ...(data.emailVerificationEnabled !== undefined && {
            emailVerificationEnabled: data.emailVerificationEnabled,
          }),
          ...(data.forgotPasswordEnabled !== undefined && {
            forgotPasswordEnabled: data.forgotPasswordEnabled,
          }),
          ...(data.polarAccessToken || data.polarWebhookSecret
            ? {
                polarAccessToken: data.polarAccessToken || null,
                polarOrganizationId: data.polarOrganizationId || null,
                polarWebhookSecret: data.polarWebhookSecret || null,
                polarSandboxMode: data.polarSandboxMode ?? undefined,
              }
            : {}),
        },
        create: {
          id: "default",
          googleClientId: hasGoogle ? data.googleClientId! : null,
          googleClientSecret: hasGoogle ? data.googleClientSecret! : null,
          socialLoginEnabled: hasSocial,
          resendApiKey: data.resendApiKey || null,
          emailVerificationEnabled: data.emailVerificationEnabled ?? false,
          forgotPasswordEnabled: data.forgotPasswordEnabled ?? true,
          polarAccessToken: data.polarAccessToken || null,
          polarOrganizationId: data.polarOrganizationId || null,
          polarWebhookSecret: data.polarWebhookSecret || null,
          polarSandboxMode: data.polarSandboxMode ?? false,
        },
      });
    } catch {
      // DB may not be migrated yet; user can add config later in Admin → API Keys
    }
  }

  return { success: true };
}

export async function generateAuthSecret() {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Buffer.from(bytes).toString("base64");
}
