"use server";

import { readFile, writeFile } from "fs/promises";
import { resolve } from "path";

import prisma from "@Batman/db";

const ENV_PATH = resolve(process.cwd(), ".env");

export async function getSetupStatus() {
  try {
    const content = await readFile(ENV_PATH, "utf-8");
    const lines = content.split("\n").filter((l) => l.trim() && !l.startsWith("#"));
    const vars: Record<string, string> = {};
    for (const line of lines) {
      const eqIdx = line.indexOf("=");
      if (eqIdx === -1) continue;
      const key = line.slice(0, eqIdx).trim();
      const val = line.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, "");
      vars[key] = val;
    }

    return {
      exists: true,
      configured: !!(vars.DATABASE_URL && vars.BETTER_AUTH_SECRET),
      vars: {
        hasDatabase: !!vars.DATABASE_URL,
        hasDirectUrl: !!vars.DIRECT_URL,
        hasAuthSecret: !!vars.BETTER_AUTH_SECRET,
        hasAuthUrl: !!vars.BETTER_AUTH_URL,
        hasCors: !!vars.CORS_ORIGIN,
        hasSupabaseUrl: !!(vars.SUPABASE_URL || vars.NEXT_PUBLIC_SUPABASE_URL),
        hasSupabaseKey: !!(vars.SUPABASE_SERVICE_ROLE_KEY || vars.NEXT_PUBLIC_SUPABASE_ANON_KEY),
        hasResend: !!vars.RESEND_API_KEY,
        hasGoogle: !!(vars.GOOGLE_CLIENT_ID && vars.GOOGLE_CLIENT_SECRET),
        hasGithub: !!(vars.GITHUB_CLIENT_ID && vars.GITHUB_CLIENT_SECRET),
      },
    };
  } catch {
    return {
      exists: false,
      configured: false,
      vars: {
        hasDatabase: false,
        hasDirectUrl: false,
        hasAuthSecret: false,
        hasAuthUrl: false,
        hasCors: false,
        hasSupabaseUrl: false,
        hasSupabaseKey: false,
        hasResend: false,
        hasGoogle: false,
        hasGithub: false,
      },
    };
  }
}

type SetupData = {
  databaseUrl: string;
  directUrl: string;
  betterAuthSecret: string;
  betterAuthUrl: string;
  corsOrigin: string;
  supabaseUrl?: string;
  supabaseAnonKey?: string;
  supabaseServiceRoleKey?: string;
  resendApiKey?: string;
  googleClientId?: string;
  googleClientSecret?: string;
  githubClientId?: string;
  githubClientSecret?: string;
  polarAccessToken?: string;
  polarOrganizationId?: string;
  polarWebhookSecret?: string;
  polarSandboxMode?: boolean;
};

export async function saveSetup(data: SetupData) {
  const lines: string[] = [
    "# Generated by Batman Setup Wizard",
    "",
    "# Auth (required)",
    `BETTER_AUTH_SECRET=${data.betterAuthSecret}`,
    `BETTER_AUTH_URL=${data.betterAuthUrl}`,
    `CORS_ORIGIN=${data.corsOrigin}`,
    "",
    "# Database (required)",
    `DATABASE_URL="${data.databaseUrl}"`,
    `DIRECT_URL="${data.directUrl}"`,
  ];

  if (data.supabaseUrl || data.supabaseAnonKey || data.supabaseServiceRoleKey) {
    lines.push("", "# Supabase (file uploads)");
    if (data.supabaseUrl) {
      lines.push(`SUPABASE_URL=${data.supabaseUrl}`);
      lines.push(`NEXT_PUBLIC_SUPABASE_URL=${data.supabaseUrl}`);
    }
    if (data.supabaseAnonKey) {
      lines.push(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${data.supabaseAnonKey}`);
    }
    if (data.supabaseServiceRoleKey) {
      lines.push(`SUPABASE_SERVICE_ROLE_KEY=${data.supabaseServiceRoleKey}`);
    }
  }

  if (data.resendApiKey) {
    lines.push("", "# Email (Resend)");
    lines.push(`RESEND_API_KEY=${data.resendApiKey}`);
  }

  if (data.googleClientId && data.googleClientSecret) {
    lines.push("", "# Google OAuth");
    lines.push(`GOOGLE_CLIENT_ID=${data.googleClientId}`);
    lines.push(`GOOGLE_CLIENT_SECRET=${data.googleClientSecret}`);
  }

  if (data.githubClientId && data.githubClientSecret) {
    lines.push("", "# GitHub OAuth");
    lines.push(`GITHUB_CLIENT_ID=${data.githubClientId}`);
    lines.push(`GITHUB_CLIENT_SECRET=${data.githubClientSecret}`);
  }

  lines.push("");

  await writeFile(ENV_PATH, lines.join("\n"), "utf-8");

  if (data.polarAccessToken || data.polarWebhookSecret) {
    try {
      await prisma.appSettings.upsert({
        where: { id: "default" },
        update: {
          polarAccessToken: data.polarAccessToken || null,
          polarOrganizationId: data.polarOrganizationId || null,
          polarWebhookSecret: data.polarWebhookSecret || null,
          polarSandboxMode: data.polarSandboxMode ?? undefined,
        },
        create: {
          id: "default",
          polarAccessToken: data.polarAccessToken || null,
          polarOrganizationId: data.polarOrganizationId || null,
          polarWebhookSecret: data.polarWebhookSecret || null,
          polarSandboxMode: data.polarSandboxMode ?? false,
        },
      });
    } catch {
      // DB may not be migrated yet; user can add Polar config later in Admin → API Keys
    }
  }

  return { success: true };
}

export async function generateAuthSecret() {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Buffer.from(bytes).toString("base64");
}
